/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-dim": "#101319",
        "on-secondary": "#3c0091",
        "on-secondary-fixed-variant": "#5516be",
        "surface-variant": "#32353c",
        "verified-green": "#00B386",
        "surface-bright": "#363940",
        "outline-variant": "#3c4a44",
        "secondary-fixed": "#e9ddff",
        "inverse-primary": "#006c52",
        "surface-container-high": "#272a31",
        "on-primary": "#003829",
        "secondary-container": "#571bc1",
        "outline": "#85948d",
        "tertiary-fixed": "#ffdcc4",
        "tertiary-fixed-dim": "#ffb781",
        "error": "#ffb4ab",
        "on-surface": "#e1e2eb",
        "on-secondary-fixed": "#23005c",
        "surface": "#101319",
        "on-error-container": "#ffdad6",
        "on-background": "#e1e2eb",
        "surface-tint": "#3edeb1",
        "inverse-on-surface": "#2e3037",
        "primary-fixed-dim": "#3edeb1",
        "surface-container-highest": "#32353c",
        "secondary-fixed-dim": "#d0bcff",
        "primary": "#56f1c2",
        "error-container": "#93000a",
        "surface-container": "#1d2026",
        "on-surface-variant": "#bbcac2",
        "on-tertiary": "#4e2600",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#6f3800",
        "inverse-surface": "#e1e2eb",
        "on-primary-fixed-variant": "#00513d",
        "on-tertiary-fixed": "#2f1400",
        "border-subtle": "#1e293b",
        "surface-container-low": "#191c22",
        "primary-fixed": "#63fccc",
        "surface-container-lowest": "#0b0e14",
        "surface-deep": "#060809",
        "text-muted": "#94a3b8",
        "on-secondary-container": "#c4abff",
        "secondary": "#d0bcff",
        "on-tertiary-container": "#773c00",
        "tertiary-container": "#ffa965",
        "primary-container": "#2dd4a7",
        "tertiary": "#ffcfad",
        "on-primary-container": "#005742",
        "background": "#101319",
        "on-primary-fixed": "#002117"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        "chat-gap": "12px",
        "gutter": "16px",
        "sidebar-width": "280px",
        "container-margin": "24px",
        "base": "8px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "mono-data": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "mono-data": ["14px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
};
